version: '3.8'

services:
    db:
        image: postgres:13
        environment:
            POSTGRES_DB: sitesdb
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - mynetwork

    web:
        build: .
        command: python pup/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8001:8000"
        depends_on:
            - db
        networks:
            - mynetwork

    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "8080:80"
        depends_on:
            - db
        networks:
            - mynetwork

networks:
    mynetwork:

volumes:
    postgres_data:
